const items = [
  [
    "Studio Wireless Headphones",
    "Electronics",
    "Audio",
    2499,
    3499,
    "headphones",
    "Comfortable over-ear wireless headphones for music and everyday listening.",
  ],
  [
    "Everyday Canvas Tote",
    "Clothes",
    "Accessories",
    699,
    999,
    "tote",
    "A roomy cotton canvas bag for everyday errands.",
  ],
  [
    "Slow Morning Mug",
    "Kitchen",
    "Drinkware",
    449,
    649,
    "mug",
    "A ceramic mug for tea, coffee, and quiet mornings.",
  ],
  [
    "Orbit Desk Lamp",
    "Electronics",
    "Lighting",
    1299,
    1799,
    "lamp",
    "An adjustable desk light for a focused workspace.",
  ],
  [
    "Classic Cotton Tee",
    "Clothes",
    "T-shirts",
    599,
    899,
    "shirt",
    "A soft cotton T-shirt with a relaxed everyday fit.",
  ],
  [
    "Daily Hydration Bottle",
    "Kitchen",
    "Drinkware",
    799,
    1099,
    "bottle",
    "A reusable insulated bottle for work and travel.",
  ],
  [
    "Pocket Bluetooth Speaker",
    "Electronics",
    "Audio",
    1499,
    1999,
    "speaker",
    "A compact portable wireless speaker for your favourite music.",
  ],
  [
    "Weekend Backpack",
    "Clothes",
    "Accessories",
    1899,
    2499,
    "backpack",
    "A versatile backpack with room for your daily essentials.",
  ],
];
const demoProducts = items.map((p, i) => ({
  _id: `65a00000000000000000000${i + 1}`,
  productName: p[0],
  category: p[1],
  subcategory: p[2],
  price: {
    cost: p[3],
    mrp: p[4],
    discountPercent: Math.round(((p[4] - p[3]) / p[4]) * 100),
  },
  productImage: `/products/${p[5]}.svg`,
  description: p[6],
  tagline: "Thoughtfully chosen for everyday life",
  quantity: 1,
  reviews: [],
  seller: { _id: "65b000000000000000000001", shopName: "Realm Studio" },
}));
module.exports = { demoProducts };
